using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Playgound.SyntaxConstructs;

namespace Playgound;

public static class SourceEmitter
{
     private const string AutoGeneratedComment = "// <auto-generated />";

     public static CompilationUnitSyntax Build()
     {
          
     }
}